[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_BASE_URL = "https://your-backend-app.herokuapp.com"

# Configuración para diferentes entornos
[context.production.environment]
  VITE_API_BASE_URL = "https://your-backend-app.herokuapp.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://your-backend-app.herokuapp.com"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://your-backend-app.herokuapp.com"